metaplex-foundation/mpl-token-auth-rules

program/src/error.rs
program/src/instruction.rs
program/src/lib.rs
program/src/payload.rs
program/src/processor.rs
program/src/state/rules.rs
program/tests/integration.rs
program/tests/utils/mod.rs

* This works around a Solita SDK generation issue.
* Also abstracts initializing and indexing into the Vec from caller.
* Would use an array but causes issues with Borsh serialization.
```
cargo build-bpf
cargo test-bpf
```

Replacing `HashMap` with `PayloadVec` type

---

README.md

Also I do see a limitation I don't like in the `PayloadVec` implementation which is basically having to define a dummy rule in order to be passed as an index.  Maybe should go back to having the user index it directly, but even then they would still have to construct a dummy rule in order to call `to_usize()` on it.

Move payload construction in README example

---

README.md
program/src/instruction.rs
program/src/lib.rs
program/src/payload.rs
program/src/processor.rs
program/src/state/rules.rs
program/tests/integration.rs

* Changing Payload type to be a struct with optional fields.
* Update test and example payload definition.

New `Payload` struct

---

README.md
packages/sdk/idl/mpl_token_auth_rules.json
packages/sdk/src/generated/errors/index.ts
program/src/error.rs
program/src/instruction.rs
program/src/payload.rs
program/src/state/rules.rs
program/tests/basic_royalty_enforcement.rs
program/tests/integration.rs

* Add pub function to allow creating Pubkey from an array of tuples.
* Add pub functions for insert, try insert, and get.
* Add doc comments for all Pubkey functions.
* Remove clone/copy from get functions by returning references (except u64).
* Modify instruction builder to take Payload type.
```
cargo build-bpf
cargo test-bpf
```

Improve `Payload` type

---

packages/sdk/idl/mpl_token_auth_rules.json
packages/sdk/src/generated/errors/index.ts
packages/sdk/src/generated/instructions/Create.ts
packages/sdk/src/generated/instructions/Validate.ts
packages/sdk/src/generated/types/CreateArgs.ts
packages/sdk/src/generated/types/ValidateArgs.ts
program/src/error.rs
program/src/instruction.rs
program/src/lib.rs
program/src/payload.rs
program/src/pda.rs
program/src/processor.rs
program/src/state/mod.rs
program/src/state/rule_set.rs
program/src/state/rules.rs
program/tests/basic_royalty_enforcement.rs
program/tests/integration.rs

* Remove need for payer to sign the validate instruction.
* Add verification that program owns the RuleSet PDA and data length is nonzero.
* Update to use constant crate ID.
* Regenerate SDK.
* Store name and owner of RuleSet in the RuleSet PDA.
* Add errors for missing accounts and missing payload values.
* Add optional accounts to create instruction.
* These are used to pass in PDAs that will be validated before
the RuleSet is stored.
* Currently this would only apply to the Frequency Rule.
* Add verification that program owns the Frequency PDA and data length is nonzero.
* Regenerating SDK.
* Docs update in: https://github.com/metaplex-foundation/mpl-token-auth-rules/pull/35
```
cargo build-bpf
cargo test-bpf
```

Remove need for payer to sign to validate

---

program/src/instruction.rs
program/src/processor.rs
program/src/state/frequency.rs
program/src/state/mod.rs
program/src/state/rules.rs
program/tests/basic_royalty_enforcement.rs
program/tests/integration.rs

* Modify SolanaAccount trait for our use case.
* Remove unused trait methods.
* Privatize one function.
* Modify `is_correct_account_type` to also check size.
* Modify Frequency rule validation to update data.
* Update the last_update field to current time.
* Make RuleSet PDA account read only during validate.
* Cleanup names and flatten if/else structure in Frequency rule.
* Add boolean flag to validate for updating Rule state.
* This flag tells validate to update any relevant state stored in Rule, such as the Frequency `last_update` time value.
* Remove size check on frequency account data per PR comment.
Do we need to use SolanaAccount 1-byte discriminator and size check given that we are following the pattern of validating PDAs?
```
cargo build-bpf
cargo test-bpf
```

Modify `SolanaAccount` trait and Frequency rule update on pass

---

program/src/instruction.rs
program/src/state/rule_set.rs
program/tests/basic_royalty_enforcement.rs
program/tests/integration.rs
program/tests/utils/mod.rs

Using Message Pack encoding, JSON objects do not deserialize correctly into a Rust `HashMap` type where the key is anything other than a `String`. This PR changes the `operation` type from `u16` to a `String` to allow proper deserialization of JavaScript-created rule sets.
It also ensures that all `RuleSet` fields are decoded correctly from `CamelCase` naming.

use String for HashMap keys

---

program/src/error.rs
program/src/instruction.rs
program/src/pda.rs
program/src/processor.rs
program/src/state/rules.rs
program/tests/basic_royalty_enforcement.rs
program/tests/integration.rs

* Right now this is written such that the Frequency rule would have an authority that must sign if frequency state is updated, and there could be a different rule with a different authority that must sign for that rule.  That seems the most future-flexible to me, but if we wanted to keep it simple we could just have one RuleSet authority at the RuleSet level that must be a signer whenever any state is meant to be updated across any rules.
* Made `payer`, `rule_authority`, and `rule_set_state_pda` optional accounts.
* Add `payer` and `rule_authority` signer accounts to `validate` instruction. 
* They do not need to be signers if Rule state is not
being updated (bool parameter is false).
* `payer` covers paying for Rule state storage.
* `rule_authority` is meant to be a signing PDA from the …

Add `rule_set_state` PDA and remove Frequency rule PDA

---

packages/sdk/package.json
packages/sdk/tsconfig.json

Currently the JS package is broken since the `src` folder is "missing". This PR changes the `tsconfig.json` to fix the root folder for yarn build.

Fix js package root path

---

program/Cargo.lock
program/Cargo.toml
program/src/entrypoint.rs
program/src/instruction.rs
program/src/processor.rs
program/src/state/rules.rs
program/tests/basic_royalty_enforcement.rs
program/tests/integration.rs

* Implement Instruction Builder using proc macro imported from token-metadata [febo/accounts-context](https://github.com/metaplex-foundation/metaplex-program-library/tree/febo/accounts-context) branch.
* Using commit hash of this branch in mpl-token-auth-rules Cargo.toml for now.
* Add `AccountContext` derivation to instruction enums.
* Port `Context` and `InstructionBuilder` structs from token-metadata (using same [febo/accounts-context](https://github.com/metaplex-foundation/metaplex-program-library/tree/febo/accounts-context) branch)
* Port `next_optional_account_info` from token-metadata.
* Add args shank annotation and implement `InstructionBuilder` trait
for `create` and `validate`.
* Modify instruction processors to use the account contexts.
* Update BPF tests to use instruction …

Using token-metadata context derive proc macro

---

README.md
program/src/instruction.rs
program/src/processor.rs
program/src/utils.rs
program/tests/basic_royalty_enforcement.rs
program/tests/integration.rs

* Remove additional rule accounts from create instruction.
* Add ability to update `RuleSet` after creation.
* Rename `Create` to `CreateOrUpdate` to match new functionality.

Add ability to update RuleSet after creation

---

packages/sdk/src/mpl-token-auth-rules.ts
packages/sdk/src/mpl-token-authorization-rules.ts

PR to fix the JS `PREFIX` value – currently the JS `PREFIX` constant does not match the program value (`ruleset` instead of `rule_set`).

Change value to match program

---

program/tests/additional_signer.rs
program/tests/all.rs
program/tests/amount.rs
program/tests/any.rs
program/tests/basic_royalty_enforcement.rs
program/tests/frequency.rs
program/tests/integration.rs
program/tests/not.rs
program/tests/pass.rs
program/tests/pda_match.rs
program/tests/program_owned.rs
program/tests/pubkey_list_match.rs
program/tests/pubkey_match.rs
program/tests/pubkey_tree_match.rs
program/tests/utils/mod.rs

* Convert several test helper functions to macros which still have the original functionality, but insert a message showing where they were called from.
* This makes it easier to debug BPF tests, i.e., so that an assertion failure doesn't just show up as the helper function's file and line number.
```
thread 'wallet_or_pda_to_wallet_or_pda' panicked at 'assertion failed: `(left == right)`
left: `ProgramOwnedListCheckFailed`,
right: `PDAMatchCheckFailed`: assert_rule_set_error called at tests/basic_royalty_enforcement.rs:574:5', tests/utils/mod.rs:201:13
```
The new part is: `assert_rule_set_error called at tests/basic_royalty_enforcement.rs:574:5`,
Instead of it only showing: `tests/utils/mod.rs:201:13`.

Adding file, line, and column to test helper functions

---

README.md
packages/sdk/idl/mpl_token_auth_rules.json
packages/sdk/src/generated/errors/index.ts
program/Cargo.lock
program/Cargo.toml
program/src/error.rs
program/src/state/rules.rs
program/tests/additional_signer.rs
program/tests/all.rs
program/tests/amount.rs
program/tests/any.rs
program/tests/basic_royalty_enforcement.rs
program/tests/frequency.rs
program/tests/integration.rs
program/tests/not.rs
program/tests/pass.rs
program/tests/pda_match.rs
program/tests/program_owned.rs
program/tests/pubkey_list_match.rs
program/tests/pubkey_match.rs
program/tests/pubkey_tree_match.rs
program/tests/utils/mod.rs

* Adding `ProgramOwnedList` rule.
* Also adding `ProgramOwnedTree` rule but currently it returns `NotImplemented`.
* Changing some of the Payload Key names in tests to more closely match what we expect token-metadata to use.
* Updating Basic Royalty Enforcement tests to have additional example RuleSets.
* Adding BPF tests including tests that check multiple pass and failure cases for the Composed Rules.
* Fixing error rollup that affected the `Any` rule from rolling up the last failed rule error.
* Regenerating SDK.  Note I did not regenerate docs.
**_NOTE ownership by System Program is NOT sufficient to prove an account is a wallet (on-curve) instead of a PDA!_**
```
OwnerTransfer:
amount is 1 &&
(source is owned by system program || (source is on allow list && source is a PDA) &&
(dest …
```

Add `ProgramOwnedList` Rule and Composed `RuleSets`

---

program/tests/additional_signer.rs
program/tests/all.rs
program/tests/amount.rs
program/tests/any.rs
program/tests/basic_royalty_enforcement.rs
program/tests/buffered_rule_set.rs
program/tests/frequency.rs
program/tests/integration.rs
program/tests/not.rs
program/tests/pda_match.rs
program/tests/program_owned.rs
program/tests/program_owned_tree_match.rs
program/tests/pubkey_list_match.rs
program/tests/pubkey_match.rs
program/tests/pubkey_tree_match.rs
program/tests/utils/mod.rs

1. Use assert_custom_error from token-metadata utils but add location
1. Prior to this had `assert_rule_set_error` and `assert_program_error` that interestingly I created completely separately from `assert_custom_error`, but the problem with `using assert_rule_set error` was that it could miscategorize other program errors for `RuleSetErrors`.
2. Instead I imported `assert_custom_error` from token-metadata and also found its  more flexible.  I just added the `file!()`, `line1()`, and `column!()` indicators and fully qualified the type paths so that the macro doesn't require other dependencies when calling it.
2. Replace payer not signer test with one that makes more sense.
1. The previous test just was trying to do unsigned transactions so the payer wasn't a signer and I don't think it …

BPF general testing updates

---

program/src/processor.rs
program/src/utils.rs

Small refactoring to add a `get_latest_revision` util method so clients can determine the latest revision available from the account data.

Add get latest revision util method

---

packages/sdk/idl/mpl_token_auth_rules.json
packages/sdk/src/generated/types/RuleSetRevisionMapV1.ts
program/src/processor.rs
program/src/state/rule_set.rs
program/tests/integration.rs

* This was originally needed for my earlier version that was array-based.
* The final design ended up using a Vec so we know the location inherently.

Removing `latest_revision` index in `RuleSet` rev map

---

packages/sdk/idl/mpl_token_auth_rules.json
packages/sdk/src/generated/errors/index.ts
program/src/error.rs
program/src/processor.rs
program/tests/integration.rs
program/tests/updated_rule_set.rs

* RuleSet update test now will validate 5 RuleSet revisions.
* Moving tests having to do with updated RuleSets to their
own file
* Adding test that creates two RuleSets and proves that the
correct RuleSet is being used.  It does this by sending inputs
that would pass for one and fail for the other and covers the
four combinations using two RuleSet revisions.
* Add test for unknown RuleSet revision.
* Also improve one error code name and regenerate IDL/SDK.
```
running 3 tests
test test_unknown_rule_set_revision_fails ... ok
test test_correct_rule_set_is_used_after_update ... ok
test test_update_ruleset_data_integrity ... ok
test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.23s
```

Modifying `RuleSet` update test and adding new tests

---

program/src/utils.rs

This PR changes (fixes) the return of the `get_latest_revision` to be the index on the revision `Vec` instead of the value (byte offset) of the latest revision.

Return revision index

---

program/src/processor.rs

This fixes the buffer overwrite issue by starting at offset 0 when overwriting the data.

Fixing offset when overwriting

---

program/src/state/rules.rs
program/tests/composed_rule.rs
program/tests/create_account_and_data_checks.rs
program/tests/integration.rs
program/tests/utils/mod.rs
program/tests/validate_account_and_data_checks.rs
program/tests/write_to_buffer_account_and_data_checks.rs

Adding tests that mostly check incoming accounts and data validation before logic occurs.  I think only `create_payer_not_signer_panics ` existed before this PR.  I put each of these instruction test suites in their own file.
```
running 9 tests
test create_payer_not_signer_panics - should panic ... ok
test create_rule_set_buffer_with_different_name_fails ... ok
test create_rule_set_to_wallet_fails ... ok
test create_rule_set_name_too_long_fails ... ok
test create_rule_set_to_wrong_pda_fails ... ok
test create_rule_set_wrong_owner_fails ... ok
test create_rule_set_empty_rule_set_fails ... ok
test create_rule_set_empty_buffer_fails ... ok
test create_rule_set_partial_buffer_fails ... ok
```
```
running 10 tests
test validate_rule_set_with_wallet_fails ... ok
test …
```

Add more BPF tests

---

program/tests/additional_signer.rs
program/tests/all.rs
program/tests/amount.rs
program/tests/any.rs
program/tests/basic_royalty_enforcement.rs
program/tests/buffered_rule_set.rs
program/tests/composed_rule.rs
program/tests/create_account_and_data_checks.rs
program/tests/frequency.rs
program/tests/is_wallet.rs
program/tests/not.rs
program/tests/pass.rs
program/tests/pda_match.rs
program/tests/program_owned.rs
program/tests/program_owned_tree_match.rs
program/tests/pubkey_list_match.rs
program/tests/pubkey_match.rs
program/tests/pubkey_tree_match.rs
program/tests/updated_rule_set.rs
program/tests/utils/mod.rs
program/tests/validate_account_and_data_checks.rs
program/tests/write_to_buffer_account_and_data_checks.rs

* Use new dev version of Royalty `RuleSet` which includes current token-metadata operations/scenarios.
* Also separating basic royalty enforcement tests into separate cases.

Update basic royalty enforcement BPF test

---

program/src/state/rules.rs

The nonzero data checks for PDA accounts in the ProgramOwned* rules can result in some unclear gotchas if people don't know the check is being performed or why the rule is failing. This PR adds some simple printouts to provide info on why the check is failing if the nonzero data check fails.

Adding helpful error prints for the nonzero data check

---

program/src/processor.rs
program/src/state/rules.rs
program/src/utils.rs
program/tests/namespace_royalty_enforcement.rs
program/tests/utils/mod.rs

Allowing for operation namespaces like delegate as fallback operations if the main operation delegate:transfer doesn't exist.

Namespacing operations.

---

program/src/state/rules.rs
program/tests/namespace_royalty_enforcement.rs

Adding pipe-separated field parsing (assumed boolean OR) to condense copy-pasted rules across different authority types.

Adding PoC multi-field system.

---

cli/examples/additional_signer.json
cli/examples/all.json
cli/examples/amount.json
cli/examples/any.json
cli/examples/derived_key_match.json
cli/examples/not.json
cli/examples/pass.json
cli/examples/program_owned.json
cli/examples/pubkey_list_match.json
cli/examples/pubkey_match.json
cli/examples/pubkey_tree_match.json
cli/src/auth.ts

Program currently throws an error on deserialization of the example JSON files, this PR makes them work again
- Updates example files to have the name field following the owner key field
- Updates indices of the ruleset that are updated before serialization in the CLI

Fix TS examples

---

packages/sdk/test/_setup.ts

PR to use the `overwrite` argument to replace the contents of the buffer account when the first "chunk" is sent to the `write_to_buffer` instruction.

Overwrite content on first chunk

---

.github/.env
.github/workflows/build-programs.yml
programs/token-auth-rules/Cargo.lock
programs/token-auth-rules/Cargo.toml

The other alternative is the community PR https://github.com/metaplex-foundation/mpl-token-auth-rules/pull/150 but we might want to leave a range at this time.
* Deleted Cargo.lock to rebuild with 1.17.
* Had to run cargo update -p ahash@0.8.7 --precise 0.8.6 to rebuild to overcome issue described here: https://solana.stackexchange.com/questions/8800/cant-build-hello-world

Update to allow Solana 1.17

---

clients/js/package.json

Needed since 3.0.2 is already deployed with alpha tag:
https://www.npmjs.com/package/@metaplex-foundation/mpl-token-auth-rules?activeTab=versions

Manually update JS package version
